### ISSUE TITLE
Compile error in ubuntu 14.04

### ISSUE THREAD

**Issue by littleseytan** [charlesveasey/vDome#10]
Hi charlesveasey,
     I am trying to compile vDome on my ubuntu 14.04 environment. I think I installed all dependencies. In OF/apps/myapps/vDome folder I just type "make" command and get the error below.

> HOST_OS=Linux
> checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 
> Compiling OF library for Release
> HOST_OS=Linux
> checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 
> make[1]: Entering directory `/home/reo-tek/Downloads/of_v0.9.1_linux64_release/libs/openFrameworksCompiled/project'
> HOST_OS=Linux
> checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 
> HOST_OS=Linux
> checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 
> Done!
> make[1]: Leaving directory`/home/reo-tek/Downloads/of_v0.9.1_linux64_release/libs/openFrameworksCompiled/project'

Compiling vDome for Release
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 
make[1]: Entering directory `/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome'
cat: obj/linux64/Release/.compiler_flags: No such file or directory
Compiling /home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/main.cpp
g++ -c -O3 -DNDEBUG -march=native -mtune=native -Wall -std=c++11 -DOF_USING_GTK -DOF_USING_GTK  -pthread -D_REENTRANT -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gstreamer-1.0 -I/usr/include/alsa -I/usr/include/libdrm -I/usr/include/GL -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/harfbuzz -I/usr/include/opencv -I../../../libs/fmodex/include -I../../../libs/glfw/include -I../../../libs/glfw/include/GLFW -I../../../libs/kiss/include -I../../../libs/poco/include -I../../../libs/tess2/include -I../../../libs/utf8cpp/include -I../../../libs/utf8cpp/include/utf8 -I../../../libs/openFrameworks -I../../../libs/openFrameworks/gl -I../../../libs/openFrameworks/utils -I../../../libs/openFrameworks/types -I../../../libs/openFrameworks/math -I../../../libs/openFrameworks/graphics -I../../../libs/openFrameworks/video -I../../../libs/openFrameworks/sound -I../../../libs/openFrameworks/app -I../../../libs/openFrameworks/communication -I../../../libs/openFrameworks/events -I../../../libs/openFrameworks/3d -pthread -D_REENTRANT -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gstreamer-1.0 -I/usr/include/alsa -I/usr/include/libdrm -I/usr/include/GL -I/usr/include/gtk-3.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/harfbuzz -I/usr/include/opencv -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/vDome.xcodeproj/project.xcworkspace -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/vDome.xcodeproj/xcshareddata -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/vDome.xcodeproj/xcshareddata/xcschemes -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/vDome.xcodeproj/xcuserdata -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/vDome.xcodeproj/xcuserdata/Charles.xcuserdatad -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/vDome.xcodeproj/xcuserdata/Charles.xcuserdatad/xcschemes -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/input -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/input/spout -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/input/spout/SpoutSDK -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/input/media -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/input/media/video -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/menu -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/renderer -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/renderer/projector -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxBezierSurface/src -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxCurvesTool/src -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxOpenCv/src -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxOpenCv/libs -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxOsc/src -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxOsc/libs -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxOsc/libs/oscpack -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxOsc/libs/oscpack/src -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxOsc/libs/oscpack/src/osc -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxOsc/libs/oscpack/src/ip -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxOsc/libs/oscpack/src/ip/win32 -I/home/reo-tek/Downloads/of_v0.9.1_linux64_release/addons/ofxOsc/libs/oscpack/src/ip/posix -I/. -I. -I./vDome.xcodeproj -I./vDome.xcodeproj/project.xcworkspace -I./vDome.xcodeproj/xcshareddata -I./vDome.xcodeproj/xcshareddata/xcschemes -I./vDome.xcodeproj/xcuserdata -I./vDome.xcodeproj/xcuserdata/Charles.xcuserdatad -I./vDome.xcodeproj/xcuserdata/Charles.xcuserdatad/xcschemes -I/./bin -I./bin -I./bin/data -I./bin/data/settings -I./bin/data/settings/shaders -I./bin/data/settings/brushes -I./bin/data/settings/media -I./bin/data/settings/media/warp -I./src -I./src/vdome -I./src/vdome/input -I./src/vdome/input/spout -I./src/vdome/input/spout/SpoutSDK -I./src/vdome/input/media -I./src/vdome/input/media/video -I./src/vdome/menu -I./src/vdome/renderer -I./src/vdome/renderer/projector -I/. -I. -I./vDome.xcodeproj -I./vDome.xcodeproj/project.xcworkspace -I./vDome.xcodeproj/xcshareddata -I./vDome.xcodeproj/xcshareddata/xcschemes -I./vDome.xcodeproj/xcuserdata -I./vDome.xcodeproj/xcuserdata/Charles.xcuserdatad -I./vDome.xcodeproj/xcuserdata/Charles.xcuserdatad/xcschemes -I/./bin -I./bin -I./bin/data -I./bin/data/settings -I./bin/data/settings/shaders -I./bin/data/settings/brushes -I./bin/data/settings/media -I./bin/data/settings/media/warp -I./src -I./src/vdome -I./src/vdome/input -I./src/vdome/input/spout -I./src/vdome/input/spout/SpoutSDK -I./src/vdome/input/media -I./src/vdome/input/media/video -I./src/vdome/menu -I./src/vdome/renderer -I./src/vdome/renderer/projector -I/. -I. -I./vDome.xcodeproj -I./vDome.xcodeproj/project.xcworkspace -I./vDome.xcodeproj/xcshareddata -I./vDome.xcodeproj/xcshareddata/xcschemes -I./vDome.xcodeproj/xcuserdata -I./vDome.xcodeproj/xcuserdata/Charles.xcuserdatad -I./vDome.xcodeproj/xcuserdata/Charles.xcuserdatad/xcschemes -I/./bin -I./bin -I./bin/data -I./bin/data/settings -I./bin/data/settings/shaders -I./bin/data/settings/brushes -I./bin/data/settings/media -I./bin/data/settings/media/warp -I./src -I./src/vdome -I./src/vdome/input -I./src/vdome/input/spout -I./src/vdome/input/spout/SpoutSDK -I./src/vdome/input/media -I./src/vdome/input/media/video -I./src/vdome/menu -I./src/vdome/renderer -I./src/vdome/renderer/projector -MMD -MP -MF obj/linux64/Release/src/main.d -MT obj/linux64/Release/src/main.o -o obj/linux64/Release/src/main.o -c /home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/main.cpp
In file included from ../../../libs/openFrameworks/math/ofVec3f.h:3:0,
                 from ../../../libs/openFrameworks/types/ofPoint.h:3,
                 from ../../../libs/openFrameworks/math/ofMath.h:3,
                 from ../../../libs/openFrameworks/types/ofColor.h:5,
                 from ../../../libs/openFrameworks/types/ofTypes.h:4,
                 from ../../../libs/openFrameworks/utils/ofLog.h:5,
                 from ../../../libs/openFrameworks/ofMain.h:7,
                 from /home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/main.cpp:1:
../../../libs/openFrameworks/math/ofVec2f.h: In member function ‘ofVec2f& ofVec2f::average(const ofVec2f*, std::size_t)’:
../../../libs/openFrameworks/math/ofVec2f.h:1363:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for( int i=0; i<num; i++) {
                  ^
In file included from /home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/vdome.h:2:0,
                 from /home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/main.cpp:2:
/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/renderer/window.h: At global scope:
/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/renderer/window.h:49:5: error: ‘Input’ does not name a type
     Input   *input;
     ^
In file included from /home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/vdome.h:4:0,
                 from /home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/main.cpp:2:
/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/menu/saveThread.h: In member function ‘virtual void SaveThread::threadedFunction()’:
/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/menu/saveThread.h:19:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for (int i=0; i <xml.size(); i++) {
                                           ^
/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/menu/saveThread.h:22:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for (int i=0; i <image.size(); i++) {
                                             ^
In file included from /home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/main.cpp:2:0:
/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/vdome.h: At global scope:
/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome/src/vdome/vdome.h:35:17: error: field ‘input’ has incomplete type
     Input       input;
                 ^
make[1]: *** [obj/linux64/Release/src/main.o] Error 1
make[1]: Leaving directory`/home/reo-tek/Downloads/of_v0.9.1_linux64_release/apps/myApps/vDome'
make: **\* [Release] Error 2

Did I miss something? Can you help me please?

--littleseytan

**Comment by avilleret** [comment]
I have the same error on Ubuntu 16.10 with Code::Blocks 16.01 and openFrameworks 0.9.8

**Comment by charlesveasey** [comment]
This is related to the version of openFrameworks you are building against. Build with oF v0.9.1.
